"""empty message

Revision ID: 3425ae293adc
Revises: 
Create Date: 2022-06-28 16:03:18.269032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3425ae293adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slugified_title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('slugified_artist', sa.String(length=100), nullable=False),
    sa.Column('lyrics', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_category',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_category')
    op.drop_table('songs')
    op.drop_table('categories')
    # ### end Alembic commands ###
